version: '3'

services:
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      - spring.mail.host=mailhog
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/task_management_system_db
#      - SPRING_DATASOURCE_USERNAME=user
#      - SPRING_DATASOURCE_PASSWORD=test@123
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
#    depends_on:
#      - DB
#      - mailhog

  DB:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=task_management_system_db'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=test@123'
    ports:
      - '5432:5432'

  mailhog:
    image: jcalonso/mailhog:latest
    ports:
      - "1025:1025"   # SMTP port
      - "8025:8025"   # Web UI port
    environment:
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=/mailhog/maildir
      - MH_SMTP_AUTH=true
      - MH_SMTP_USERNAME=smtpuser
      - MH_SMTP_PASSWORD=strongpassword